export default function personalizedBookB(student, car) {
  if (!student || !student.lastName || !student.firstName || !student.birthDate) {
    console.error('Ошибка: данные о студенте отсутствуют');
    return null;
  }

  return {
    content: [
      { text: 'Учет обучения вождению транспортного средства категории "В"', style: 'header' },
      {
        text: `c ${car?.carTransmission === 'mkp' ? 'механической' : 'автоматической'} трансмиссией`,
        style: 'header',
        margin: [0, 0, 0, 3],
      },
      {
        table: {
          widths: ['8%', '3.5%', '3.5%', '43%', '8%', '8%', '4%', '10%', '10%'],
          body: [
            [
              {
                rowSpan: 2,
                text: 'Дата',
                style: 'tableHeader',
                margin: [0, 25, 0, 0],
              },
              {
                colSpan: 2,
                text: '№ тем',
                style: 'tableHeader',
              },
              {},
              {
                rowSpan: 2,
                text: 'Наименование разделов, тем и занятий',
                style: 'tableHeader',
                margin: [0, 25, 0, 0],
              },
              {
                colSpan: 2,
                text: 'Количество часов практического обучения',
                style: 'tableHeader',
              },
              {},
              {
                rowSpan: 2,
                text: 'Оценка',
                style: 'tableHeader',
                margin: [0, 25, 0, 0],
              },
              {
                colSpan: 2,
                text: 'Подпись',
                style: 'tableHeader',
              },
              {},
            ],
            [
              {},
              {
                text: [{ text: 'М' }, { text: '1', fontSize: 6, margin: [0, 0, 0, 5] }],
                style: 'tableHeader',
                margin: [0, 15, 0, 0],
              },
              {
                text: ['А', { text: '2', fontSize: 6, margin: [0, -5] }],
                style: 'tableHeader',
                margin: [0, 15, 0, 0],
              },
              {},
              { text: 'По учебному плану', style: 'tableHeader' },
              { text: 'Выполнено', style: 'tableHeader' },
              {},
              { text: 'Мастер производственного обучения', style: 'tableHeader' },
              { text: 'Обучающийся', style: 'tableHeader' },
            ],
            [
              {},
              {},
              {},
              { text: '1. Первоначальное обучение вождению', fontSize: 8, bold: true },
              {},
              {},
              {},
              {},
              {},
            ],
            [
              {},
              { text: '1.1', fontSize: 6 },
              {},
              { text: 'Посадка, действие органами управления', fontSize: 6 },
              { text: '2', fontSize: 6, alignment: 'center' },
              {},
              {},
              {},
              {},
            ],
            [
              {},
              {},
              { text: '1.1', fontSize: 6 },
              {
                text: 'Посадка, пуск двигателя, действие органами управления при увеличении и уменьшении скорости движения, остановка, выключение двигателя',
                fontSize: 6,
              },
              { text: '2', fontSize: 6, alignment: 'center' },
              {},
              {},
              {},
              {},
            ],
            [
              {},
              {},
              { text: '1.2', fontSize: 6 },
              {
                text: 'Пуск двигателя, начало движения, переключение передач в восходящем порядке, переключение передач в нисходящем порядке, остановка, выключение двигателя',
                fontSize: 6,
              },
              { text: '2', fontSize: 6, alignment: 'center' },
              {},
              {},
              {},
              {},
            ],
            [
              {},
              { text: '1.3', fontSize: 6 },
              { text: '1.2', fontSize: 6 },
              {
                text: 'Начало движения, движение по кольцевому маршруту, остановка в заданном месте с применением различных способов торможения',
                fontSize: 6,
              },
              { text: '2', fontSize: 6, alignment: 'center' },
              {},
              {},
              {},
              {},
            ],
            [
              {},
              { text: '1.3', fontSize: 6 },
              { text: '1.2', fontSize: 6 },
              {
                text: 'Начало движения, движение по кольцевому маршруту, остановка в заданном месте с применением различных способов торможения',
                fontSize: 6,
              },
              { text: '2', fontSize: 6, alignment: 'center' },
              {},
              {},
              {},
              {},
            ],
            [
              {},
              { text: '1.4', fontSize: 6 },
              { text: '1.3', fontSize: 6 },
              {
                text: 'Повороты в движении, разворот для движения в обратном направлении, проезд перекрестка и пешеходного перехода',
                fontSize: 6,
              },
              { text: '2', fontSize: 6, alignment: 'center' },
              {},
              {},
              {},
              {},
            ],
            [
              {},
              { text: '1.5', fontSize: 6 },
              { text: '1.4', fontSize: 6 },
              {
                text: 'Движение задним ходом',
                fontSize: 6,
              },
              { text: '1', fontSize: 6, alignment: 'center' },
              {},
              {},
              {},
              {},
            ],
            [
              {},
              { text: '1.6', fontSize: 6 },
              { text: '1.5', fontSize: 6 },
              {
                text: 'Движение в ограниченных проездах, сложное маневрирование',
                fontSize: 6,
              },
              { text: '1', fontSize: 6, alignment: 'center' },
              {},
              {},
              {},
              {},
            ],
            [
              {},
              { text: '1.6', fontSize: 6 },
              { text: '1.5', fontSize: 6 },
              {
                text: 'Движение в ограниченных проездах, сложное маневрирование',
                fontSize: 6,
              },
              { text: '2', fontSize: 6, alignment: 'center' },
              {},
              {},
              {},
              {},
            ],
            [
              {},
              { text: '1.6', fontSize: 6 },
              { text: '1.5', fontSize: 6 },
              {
                text: 'Движение в ограниченных проездах, сложное маневрирование',
                fontSize: 6,
              },
              { text: '2', fontSize: 6, alignment: 'center' },
              {},
              {},
              {},
              {},
            ],
            [
              {},
              { text: '1.6', fontSize: 6 },
              { text: '1.5', fontSize: 6 },
              {
                text: 'Движение в ограниченных проездах, сложное маневрирование',
                fontSize: 6,
              },
              { text: '2', fontSize: 6, alignment: 'center' },
              {},
              {},
              {},
              {},
            ],
            [{ text: '', margin: [0, 6, 0, 0] }, {}, {}, {}, {}, {}, {}, {}, {}],
            [
              {},
              {},
              {},
              {
                text: [
                  { text: 'Контрольное задание №1', fontSize: 8, bold: true },
                  { text: '3', fontSize: 6, margin: [0, -5] },
                ],
              },
              {},
              {},
              {},
              {},
              {},
            ],
            [
              {},
              { text: '1.7', fontSize: 6 },
              { text: '1.6', fontSize: 6 },
              { text: 'Движение с прицепом 4', fontSize: 6 },
              { text: '2', fontSize: 6, alignment: 'center' },
              {},
              {},
              {},
              {},
            ],
            [
              {},
              { text: '1.7', fontSize: 6 },
              { text: '1.6', fontSize: 6 },
              { text: 'Движение с прицепом 4', fontSize: 6 },
              { text: '2', fontSize: 6, alignment: 'center' },
              {},
              {},
              {},
              {},
            ],
            [
              {},
              { text: '1.7', fontSize: 6 },
              { text: '1.6', fontSize: 6 },
              { text: 'Движение с прицепом 4', fontSize: 6 },
              { text: '2', fontSize: 6, alignment: 'center' },
              {},
              {},
              {},
              {},
            ],
            [{}, {}, {}, { text: 'Итого по разделу', fontSize: 6, bold: true }, {}, {}, {}, {}, {}],
            [{ text: '', margin: [0, 6, 0, 0] }, {}, {}, {}, {}, {}, {}, {}, {}],
            [
              {},
              {},
              {},
              {
                text: '2. Обучение вождению в условиях дорожного движения',
                fontSize: 8,
                bold: true,
              },
              {},
              {},
              {},
              {},
              {},
            ],
            [
              {},
              { text: '2.1', fontSize: 6 },
              { text: '2.1', fontSize: 6 },
              { text: 'Вождение по учебным маршрутам', fontSize: 6 },
              { text: '2', fontSize: 6, alignment: 'center' },
              {},
              {},
              {},
              {},
            ],
            [
              {},
              { text: '2.1', fontSize: 6 },
              { text: '2.1', fontSize: 6 },
              { text: 'Вождение по учебным маршрутам', fontSize: 6 },
              { text: '2', fontSize: 6, alignment: 'center' },
              {},
              {},
              {},
              {},
            ],
            [
              {},
              { text: '2.1', fontSize: 6 },
              { text: '2.1', fontSize: 6 },
              { text: 'Вождение по учебным маршрутам', fontSize: 6 },
              { text: '2', fontSize: 6, alignment: 'center' },
              {},
              {},
              {},
              {},
            ],
            [
              {},
              { text: '2.1', fontSize: 6 },
              { text: '2.1', fontSize: 6 },
              { text: 'Вождение по учебным маршрутам', fontSize: 6 },
              { text: '2', fontSize: 6, alignment: 'center' },
              {},
              {},
              {},
              {},
            ],
            [
              {},
              { text: '2.1', fontSize: 6 },
              { text: '2.1', fontSize: 6 },
              { text: 'Вождение по учебным маршрутам', fontSize: 6 },
              { text: '2', fontSize: 6, alignment: 'center' },
              {},
              {},
              {},
              {},
            ],
            [
              {},
              { text: '2.1', fontSize: 6 },
              { text: '2.1', fontSize: 6 },
              { text: 'Вождение по учебным маршрутам', fontSize: 6 },
              { text: '2', fontSize: 6, alignment: 'center' },
              {},
              {},
              {},
              {},
            ],
            [
              {},
              { text: '2.1', fontSize: 6 },
              { text: '2.1', fontSize: 6 },
              { text: 'Вождение по учебным маршрутам', fontSize: 6 },
              { text: '2', fontSize: 6, alignment: 'center' },
              {},
              {},
              {},
              {},
            ],
            [
              {},
              { text: '2.1', fontSize: 6 },
              { text: '2.1', fontSize: 6 },
              { text: 'Вождение по учебным маршрутам', fontSize: 6 },
              { text: '2', fontSize: 6, alignment: 'center' },
              {},
              {},
              {},
              {},
            ],
            [
              {},
              { text: '2.1', fontSize: 6 },
              { text: '2.1', fontSize: 6 },
              { text: 'Вождение по учебным маршрутам', fontSize: 6 },
              { text: '2', fontSize: 6, alignment: 'center' },
              {},
              {},
              {},
              {},
            ],
            [
              {},
              { text: '2.1', fontSize: 6 },
              { text: '2.1', fontSize: 6 },
              { text: 'Вождение по учебным маршрутам', fontSize: 6 },
              { text: '2', fontSize: 6, alignment: 'center' },
              {},
              {},
              {},
              {},
            ],
            [
              {},
              { text: '2.1', fontSize: 6 },
              { text: '2.1', fontSize: 6 },
              { text: 'Вождение по учебным маршрутам', fontSize: 6 },
              { text: '2', fontSize: 6, alignment: 'center' },
              {},
              {},
              {},
              {},
            ],
            [
              {},
              { text: '2.1', fontSize: 6 },
              { text: '2.1', fontSize: 6 },
              { text: 'Вождение по учебным маршрутам', fontSize: 6 },
              { text: '2', fontSize: 6, alignment: 'center' },
              {},
              {},
              {},
              {},
            ],
            [
              {},
              { text: '2.1', fontSize: 6 },
              { text: '2.1', fontSize: 6 },
              { text: 'Вождение по учебным маршрутам', fontSize: 6 },
              { text: '2', fontSize: 6, alignment: 'center' },
              {},
              {},
              {},
              {},
            ],
            [
              {},
              { text: '2.1', fontSize: 6 },
              { text: '2.1', fontSize: 6 },
              { text: 'Вождение по учебным маршрутам', fontSize: 6 },
              { text: '2', fontSize: 6, alignment: 'center' },
              {},
              {},
              {},
              {},
            ],
            [
              {},
              { text: '2.1', fontSize: 6 },
              { text: '2.1', fontSize: 6 },
              { text: 'Вождение по учебным маршрутам', fontSize: 6 },
              { text: '2', fontSize: 6, alignment: 'center' },
              {},
              {},
              {},
              {},
            ],
            [
              {},
              { text: '2.1', fontSize: 6 },
              { text: '2.1', fontSize: 6 },
              { text: 'Вождение по учебным маршрутам', fontSize: 6 },
              { text: '2', fontSize: 6, alignment: 'center' },
              {},
              {},
              {},
              {},
            ],
            [{ text: '', margin: [0, 6, 0, 0] }, {}, {}, {}, {}, {}, {}, {}, {}],
            [
              {},
              {},
              {},
              {
                text: [
                  { text: 'Контрольное задание №2', fontSize: 8, bold: true },
                  { text: '5', fontSize: 6, margin: [0, -5] },
                ],
              },
              {},
              {},
              {},
              {},
              {},
            ],
            [{}, {}, {}, { text: 'Итого по разделу', fontSize: 6, bold: true }, {}, {}, {}, {}, {}],
            [{ text: '', margin: [0, 6, 0, 0] }, {}, {}, {}, {}, {}, {}, {}, {}],
            [{}, {}, {}, { text: 'Итого', fontSize: 6, bold: true }, {}, {}, {}, {}, {}],

            // [{}, {}, {}, {}, {}, {}, {}, {}, {}],
          ],
        },
      },
      { text: 'Примечание:', fontSize: 10, margin: [0, 3, 0, 0] },
      { text: '1. Для учебных транспортных средств с механической трансмиссией', fontSize: 10 },
      { text: '2. Для учебных транспортных средств с автоматической трансмиссией', fontSize: 10 },
      {
        text: '3. Выполнение контрольного задания №1 проводится за счет часов темы 1.6 (1.5)',
        fontSize: 10,
      },
      {
        text: '4. Обучение проводится по желанию обучающегося. Часы могут распределяться на изучение других тем по разделу. Для выполнения задания используется прицеп, разрешенная максимальная масса которого не превышает 750 кг.',
        fontSize: 10,
      },
      {
        text: '5. Выполнение контрольного задания №2 проводится за счет часов темы 2.1',
        fontSize: 10,
      },
    ],
    styles: {
      header: { bold: true, alignment: 'center' },
      tableHeader: { fontSize: 8, alignment: 'center' },
    },
  };
}
